// <auto-generated />
using System;
using Expense.Domain.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Expense.Domain.Migrations
{
    [DbContext(typeof(ExpenseDbContext))]
    [Migration("20260716150123_AddImportRuns")]
    partial class AddImportRuns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Expense.Domain.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("ExtraPayment")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("extra_payment");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<decimal?>("MinPayment")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("min_payment");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int?>("PaymentDueDay")
                        .HasColumnType("integer")
                        .HasColumnName("payment_due_day");

                    b.Property<int?>("StatementCloseDay")
                        .HasColumnType("integer")
                        .HasColumnName("statement_close_day");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_accounts_name");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("Expense.Domain.Entities.AmazonOrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ItemTitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("item_title");

                    b.Property<DateOnly>("OrderDate")
                        .HasColumnType("date")
                        .HasColumnName("order_date");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("order_id");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("price");

                    b.Property<int?>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<decimal?>("RefundAmount")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("refund_amount");

                    b.Property<decimal>("TaxAllocated")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("tax_allocated");

                    b.HasKey("Id")
                        .HasName("pk_amazon_order_items");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_amazon_order_items_category_id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_amazon_order_items_order_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_amazon_order_items_product_id");

                    b.ToTable("amazon_order_items", (string)null);
                });

            modelBuilder.Entity("Expense.Domain.Entities.BankTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DedupFingerprint")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("dedup_fingerprint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_id");

                    b.Property<string>("ImportSource")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("import_source");

                    b.Property<bool>("IsAmazonMerchant")
                        .HasColumnType("boolean")
                        .HasColumnName("is_amazon_merchant");

                    b.Property<string>("Merchant")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("merchant");

                    b.Property<DateOnly?>("PostedDate")
                        .HasColumnType("date")
                        .HasColumnName("posted_date");

                    b.Property<DateOnly>("TransactionDate")
                        .HasColumnType("date")
                        .HasColumnName("transaction_date");

                    b.HasKey("Id")
                        .HasName("pk_bank_transactions");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_bank_transactions_category_id");

                    b.HasIndex("DedupFingerprint")
                        .IsUnique()
                        .HasDatabaseName("ix_bank_transactions_dedup_fingerprint")
                        .HasFilter("dedup_fingerprint IS NOT NULL");

                    b.HasIndex("AccountId", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_bank_transactions_account_id_external_id")
                        .HasFilter("external_id IS NOT NULL");

                    b.ToTable("bank_transactions", (string)null);
                });

            modelBuilder.Entity("Expense.Domain.Entities.BudgetPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<DateOnly?>("Anchor")
                        .HasColumnType("date")
                        .HasColumnName("anchor");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Expense")
                        .HasColumnName("direction");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<DateOnly?>("EffectiveThrough")
                        .HasColumnType("date")
                        .HasColumnName("effective_through");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("frequency");

                    b.HasKey("Id")
                        .HasName("pk_budget_periods");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_budget_periods_account_id");

                    b.HasIndex("CategoryId", "EffectiveFrom")
                        .HasDatabaseName("ix_budget_periods_category_id_effective_from");

                    b.ToTable("budget_periods", (string)null);
                });

            modelBuilder.Entity("Expense.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_categories_name");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("Expense.Domain.Entities.CheckingBalanceSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("AsOfDate")
                        .HasColumnType("date")
                        .HasColumnName("as_of_date");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("balance");

                    b.HasKey("Id")
                        .HasName("pk_checking_balance_snapshots");

                    b.HasIndex("AsOfDate")
                        .HasDatabaseName("ix_checking_balance_snapshots_as_of_date");

                    b.ToTable("checking_balance_snapshots", (string)null);
                });

            modelBuilder.Entity("Expense.Domain.Entities.DebtBalanceSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<DateOnly>("AsOfDate")
                        .HasColumnType("date")
                        .HasColumnName("as_of_date");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("balance");

                    b.HasKey("Id")
                        .HasName("pk_debt_balance_snapshots");

                    b.HasIndex("AccountId", "AsOfDate")
                        .HasDatabaseName("ix_debt_balance_snapshots_account_id_as_of_date");

                    b.ToTable("debt_balance_snapshots", (string)null);
                });

            modelBuilder.Entity("Expense.Domain.Entities.FundingRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<string>("Strategy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("strategy");

                    b.HasKey("Id")
                        .HasName("pk_funding_rules");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_funding_rules_account_id");

                    b.HasIndex("CategoryId")
                        .IsUnique()
                        .HasDatabaseName("ix_funding_rules_category_id");

                    b.ToTable("funding_rules", (string)null);
                });

            modelBuilder.Entity("Expense.Domain.Entities.ImportRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<DateTimeOffset>("RanAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ran_at");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean")
                        .HasColumnName("success");

                    b.Property<string>("Summary")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("summary");

                    b.HasKey("Id")
                        .HasName("pk_import_runs");

                    b.HasIndex("Source", "RanAt")
                        .HasDatabaseName("ix_import_runs_source_ran_at");

                    b.ToTable("import_runs", (string)null);
                });

            modelBuilder.Entity("Expense.Domain.Entities.MerchantRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<string>("MerchantPattern")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("merchant_pattern");

                    b.HasKey("Id")
                        .HasName("pk_merchant_rules");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_merchant_rules_category_id");

                    b.ToTable("merchant_rules", (string)null);
                });

            modelBuilder.Entity("Expense.Domain.Entities.OneTimeEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("direction");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_one_time_events");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_one_time_events_account_id");

                    b.HasIndex("Date")
                        .HasDatabaseName("ix_one_time_events_date");

                    b.ToTable("one_time_events", (string)null);
                });

            modelBuilder.Entity("Expense.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<string>("ProductPattern")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("product_pattern");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_products_category_id");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("Expense.Domain.Entities.AmazonOrderItem", b =>
                {
                    b.HasOne("Expense.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("fk_amazon_order_items_categories_category_id");

                    b.HasOne("Expense.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .HasConstraintName("fk_amazon_order_items_products_product_id");

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Expense.Domain.Entities.BankTransaction", b =>
                {
                    b.HasOne("Expense.Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bank_transactions_accounts_account_id");

                    b.HasOne("Expense.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("fk_bank_transactions_categories_category_id");

                    b.Navigation("Account");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Expense.Domain.Entities.BudgetPeriod", b =>
                {
                    b.HasOne("Expense.Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .HasConstraintName("fk_budget_periods_accounts_account_id");

                    b.HasOne("Expense.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_budget_periods_categories_category_id");

                    b.Navigation("Account");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Expense.Domain.Entities.DebtBalanceSnapshot", b =>
                {
                    b.HasOne("Expense.Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_debt_balance_snapshots_accounts_account_id");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Expense.Domain.Entities.FundingRule", b =>
                {
                    b.HasOne("Expense.Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .HasConstraintName("fk_funding_rules_accounts_account_id");

                    b.HasOne("Expense.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_funding_rules_categories_category_id");

                    b.Navigation("Account");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Expense.Domain.Entities.MerchantRule", b =>
                {
                    b.HasOne("Expense.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_merchant_rules_categories_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Expense.Domain.Entities.OneTimeEvent", b =>
                {
                    b.HasOne("Expense.Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_one_time_events_accounts_account_id");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Expense.Domain.Entities.Product", b =>
                {
                    b.HasOne("Expense.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_products_categories_category_id");

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
